services:
    mysql:
        image: mysql:${MYSQL_VERSION:-8.4.6}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-prestashop}
            MYSQL_RANDOM_ROOT_PASSWORD: "true"
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-prestashop}
            MYSQL_USER: ${MYSQL_USER:-prestashop}
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - ./.volumes/mysql:/var/lib/mysql:rw

    postgres:
        image: postgres:${POSTGRES_VERSION:-17.6}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-prestashop}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-prestashop}
            POSTGRES_USER: ${POSTGRES_USER:-prestashop}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-prestashop}", "-U", "${POSTGRES_USER:-prestashop}"]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - ./.volumes/postgresql:/var/lib/postgresql/data
    
    redis:
        image: redis:${REDIS_VERSION:-8.2.1}-alpine
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            timeout: 5s
            retries: 5
            start_period: 60s

    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-4.1.4}-management-alpine
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia/:rw

    mailer:
        image: axllent/mailpit:${MAILPIT_VERSION:-v1.27}
        environment:
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
