services:
    mysql:
        image: mysql:${MYSQL_VERSION:-8.0}
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./.volumes/mysql:/var/lib/mysql:rw

    postgres:
        image: postgres:${POSTGRES_VERSION:-16}-alpine
        environment:
          - POSTGRES_DB=${POSTGRES_DB:-faume}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-faume}
          - POSTGRES_USER=${POSTGRES_USER:-faume}
        ports:
            - "5432:5432"
        volumes:
          - ./.volumes/postgresql:/var/lib/postgresql/data
    
    redis:
        image: redis:${REDIS_VERSION:-alpine}
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-management-alpine}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia/:rw

    mailhog:
        image: mailhog/mailhog
        platform: linux/amd64
        logging:
            driver: 'none'
        ports:
            - "1025:1025"
            - "8025:8025"

    meilisearch:
        image: getmeili/meilisearch:${MEILI_VERSION:-v1.4}
        ports:
            - "7700:7700"
        volumes:
            - ./.volumes/meilisearch:/meili_data:rw
            - ./meilisearch/config.toml:/meili_data/config.toml:rw
        environment:
            MEILI_CONFIG_FILE_PATH: "${MEILI_CONFIG_FILE_PATH:-./config.toml}"
            MEILI_MASTER_KEY: "${MEILI_MASTER_KEY:-masterKey}"
