services:
    mysql:
        ports:
            - "3306:3306"

    postgres:
        ports:
            - "5432:5432"
    
    redis:
        ports:
            - "6379:6379"

    rabbitmq:
        ports:
            - "5672:5672"
            - "15672:15672"

    mailer:
        ports:
            - "1025:1025"
            - "8025:8025"
