version: "3.8"

services:
    db:
        image: mysql:${MYSQL_VERSION:-8.0}
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./.volumes/db:/var/lib/mysql:rw

    redis:
        image: redis:${REDIS_VERSION:-alpine}
        ports:
            - "6379:6379"
  
    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-management-alpine}
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia/:rw

    meilisearch:
        image: getmeili/meilisearch:${MEILI_VERSION:-v1.4}
        ports:
            - "7700:7700"
        volumes:
            - ./.volumes/meilisearch:/meili_data:rw
            - ./meilisearch/config.toml:/meili_data/config.toml:rw
        environment:
            MEILI_CONFIG_FILE_PATH: "${MEILI_CONFIG_FILE_PATH:-./config.toml}"
            MEILI_MASTER_KEY: "${MEILI_MASTER_KEY:-masterKey}"
