version: "3.8"

services:
    mariadb:
        image: mariadb:${MARIADB_VERSION:-latest}
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./.volumes/mariadb/:/var/lib/mysql/:rw

    redis:
        image: redis:${POSTGRES_VERSION:-alpine}
        container_name: redis
        restart: always
        ports:
            - 6379:6379
  
    rabbitmq:
        image: rabbitmq:${RABBITMQ_VERSION:-management-alpine}
        container_name: rabbitmq
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./.volumes/rabbitmq/data/:/var/lib/rabbitmq/mnesia/:rw
